= Booster - Smart cache for Enonic sites

Supercharge sites rendered with the Enonic framework

== About

Booster caches pages rendered with the Enonic framework/site engine. It is useful for sites that have a lot of traffic, or simply for getting faster pages.

Booster is built to be highly effective, without the typical side-effects of html caching - meaning it will automaticall determine what content can be cached, and automatically invalidate cache when content is published.

NOTE: Booster will not work without a valid Enonic license

=== Ignore booster if

If you are using 3.rd party front-end frameworks, or doing heavy server-side personalization - Booster is probably not relevant.


== Features

Here are the essential capabilities provided:

- Enable on a per site level
- Control default TTL per site
- Exclude specific paths from cache
- Only caches published content (ignores draft items)
- Invalidates cache on application start
- Invalidates cache on content publish
- Invalidate cache via UI or API
- Serves Brotli or Gzip compressed content
- Cache is shared across entire XP cluster
- Cache survives XP restart
- Excludes named query parameters from cache key
- Caches only specific MIME types (defaults to html/xhtml)
- Implements 304 Not Modified headers
- Respects max-age and s-maxage headers
- Optionally control downstream cache headers
- Control cache size (max items in cache)
- Provides `Cache-Status` and `Age` headers
- Mitigates thundering herd via request collapsing
