= Usage

== Cache Invalidation

=== Automatic Cache Invalidation

The cache is automatically invalidated when the following events occur:
- Application listed in `appsInvalidateCacheOnStart` starts. The entire cache is invalidated.
- Content is published/unpublished. The cache is invalidated for the published Content's Project.
- Content scheduled for publishing/unpublishing reaches its scheduled time. The cache invalidated for the scheduled Content's Project.
- Project deleted. The cache invalidated for the deleted Project.
- Cache item expired meaning Time to live (TTL) for the cache item is reached.

=== Manual Cache Invalidation

The cache can be manually invalidated in Content Studio widget. Only entire project cache can be invalidated.
Only Project Owners and System Administrators have access to the widget.

=== Programmatic Cache Invalidation

There are two tasks that can be used to invalidate the cache programmatically:
- `com.enonic.app.booster:invalidate`
- `com.enonic.app.booster:purge-all`

